# Generated by Django 3.2.4 on 2021-06-24 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='proile_image',
            new_name='profile_image',
        ),
    ]
